export * from './confirmed-booking/confirmed-booking.component'
export * from './history/history.component'
export * from './movie-details/movie-details.component'
export * from './mybooking/mybooking.component'
export * from './user.component'